# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView_client = QtWidgets.QListView(self.centralwidget)
        self.listView_client.setGeometry(QtCore.QRect(30, 50, 331, 192))
        self.listView_client.setObjectName("listView_client")
        self.btn_start_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_test.setGeometry(QtCore.QRect(400, 50, 131, 51))
        self.btn_start_test.setObjectName("btn_start_test")
        self.btn_stop_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop_test.setGeometry(QtCore.QRect(400, 140, 131, 51))
        self.btn_stop_test.setObjectName("btn_stop_test")
        self.label_profile_per_sec = QtWidgets.QLabel(self.centralwidget)
        self.label_profile_per_sec.setGeometry(QtCore.QRect(40, 300, 151, 31))
        self.label_profile_per_sec.setObjectName("label_profile_per_sec")
        self.label_profile_total = QtWidgets.QLabel(self.centralwidget)
        self.label_profile_total.setGeometry(QtCore.QRect(40, 340, 151, 31))
        self.label_profile_total.setObjectName("label_profile_total")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MulticastServerTester"))
        self.btn_start_test.setText(_translate("MainWindow", "Start Test"))
        self.btn_stop_test.setText(_translate("MainWindow", "Stop Test"))
        self.label_profile_per_sec.setText(_translate("MainWindow", "Speed:   MBs"))
        self.label_profile_total.setText(_translate("MainWindow", "Total:   MBs"))
